-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 11:28:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tabnova_iot_sample
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tabnova_iot_sample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tabnova_iot_sample` DEFAULT CHARACTER SET utf8 ;
USE `tabnova_iot_sample` ;

-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`truck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`truck` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`compartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`compartment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `truck_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `truck_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_compartment_truck1_idx` (`truck_id` ASC),
  CONSTRAINT `fk_compartment_truck1`
    FOREIGN KEY (`truck_id`)
    REFERENCES `tabnova_iot_sample`.`truck` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`sensor` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sid` VARCHAR(45) NOT NULL,
  `compartment_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `compartment_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `serial_UNIQUE` (`sid` ASC),
  INDEX `fk_sensor_compartment1_idx` (`compartment_id` ASC),
  CONSTRAINT `fk_sensor_compartment1`
    FOREIGN KEY (`compartment_id`)
    REFERENCES `tabnova_iot_sample`.`compartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`reading` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sensor_id` INT(11) UNSIGNED NOT NULL,
  `temperature` INT(11) NULL DEFAULT NULL,
  `pressure` INT(11) NULL DEFAULT NULL,
  `humidity` INT(11) NULL DEFAULT NULL,
  `battery` INT(11) NULL DEFAULT NULL,
  `acceleration` INT(11) NULL DEFAULT NULL,
  `rSSI` INT(11) NULL DEFAULT NULL,
  `geo_location` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `sensor_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_reading_sensor1_idx` (`sensor_id` ASC),
  CONSTRAINT `fk_reading_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `tabnova_iot_sample`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 705
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`retailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`retailer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`warehouse` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tabnova_iot_sample`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabnova_iot_sample`.`delivery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `truck_id` INT UNSIGNED NOT NULL,
  `retailer_id` INT UNSIGNED NOT NULL,
  `warehouse_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `truck_id`, `retailer_id`, `warehouse_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_delivery_truck1_idx` (`truck_id` ASC),
  INDEX `fk_delivery_retailer1_idx` (`retailer_id` ASC),
  INDEX `fk_delivery_warehouse1_idx` (`warehouse_id` ASC),
  CONSTRAINT `fk_delivery_truck1`
    FOREIGN KEY (`truck_id`)
    REFERENCES `tabnova_iot_sample`.`truck` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_retailer1`
    FOREIGN KEY (`retailer_id`)
    REFERENCES `tabnova_iot_sample`.`retailer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_warehouse1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `tabnova_iot_sample`.`warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
